
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vamsilingamaneni
 */
public class ParkOfficeGUI extends javax.swing.JFrame {

	/**
	 * Creates new form ParkOfficeGUI
	 */
	public ParkOfficeGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButtonParkStatus = new javax.swing.JButton();
		jButtonRemoveSpace = new javax.swing.JButton();
		jButtonAddSpace = new javax.swing.JButton();
		jButtonGrantRequest = new javax.swing.JButton();
		jLabelLicensePlate = new javax.swing.JLabel();
		jLabelParkingSpot = new javax.swing.JLabel();
		jLabelBookID = new javax.swing.JLabel();
		jLabelValid = new javax.swing.JLabel();
		jTextFieldLicense1 = new javax.swing.JTextField();
		jComboBoxParkingSpot = new javax.swing.JComboBox<>();
		jLabelPayment = new javax.swing.JLabel();
		jLabelValid1 = new javax.swing.JLabel();
		jButtonCancelRequest = new javax.swing.JButton();
		jLabelValid2 = new javax.swing.JLabel();
		jLabelDuration = new javax.swing.JLabel();
		jLabelValid3 = new javax.swing.JLabel();
		jLabelTime = new javax.swing.JLabel();
		jLabelVerfication = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jButtonLogout = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(89, 98, 117));

		jButtonParkStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonParkStatus.setText("Parking Status");
		jButtonParkStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonParkStatus.addMouseListener(new java.awt.event.MouseAdapter() {

		});
		jButtonParkStatus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonParkStatusActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButtonRemoveSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonRemoveSpace.setText("Remove Space");
		jButtonRemoveSpace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonRemoveSpace.addMouseListener(new java.awt.event.MouseAdapter() {

		});
		jButtonRemoveSpace.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRemoveSpaceActionPerformed(evt);
			}
		});

		jButtonAddSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonAddSpace.setText("Add Space");
		jButtonAddSpace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonAddSpace.addMouseListener(new java.awt.event.MouseAdapter() {

		});
		jButtonAddSpace.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddSpaceActionPerformed(evt);
			}
		});

		jButtonGrantRequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonGrantRequest.setText("Grant Request");
		jButtonGrantRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonGrantRequest.addMouseListener(new java.awt.event.MouseAdapter() {

		});
		jButtonGrantRequest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonGrantRequestActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabelLicensePlate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelLicensePlate.setForeground(new java.awt.Color(255, 255, 255));
		jLabelLicensePlate.setText("License Plate:");

		jLabelParkingSpot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelParkingSpot.setForeground(new java.awt.Color(255, 255, 255));
		jLabelParkingSpot.setText("Parking spot:");

		jLabelBookID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelBookID.setForeground(new java.awt.Color(255, 255, 255));

		jLabelValid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelValid.setForeground(new java.awt.Color(255, 255, 255));
		jLabelValid.setText("Payment Status:");

		jTextFieldLicense1.setBackground(new java.awt.Color(108, 122, 137));
		jTextFieldLicense1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jTextFieldLicense1.setForeground(new java.awt.Color(255, 255, 255));
		jTextFieldLicense1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLicense1ActionPerformed(evt);
			}
		});

		jComboBoxParkingSpot.setBackground(new java.awt.Color(108, 122, 137));
		jComboBoxParkingSpot.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
		jComboBoxParkingSpot.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxParkingSpotActionPerformed(evt);
			}
		});

		jLabelPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelPayment.setForeground(new java.awt.Color(255, 255, 255));

		jLabelValid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelValid1.setForeground(new java.awt.Color(255, 255, 255));
		jLabelValid1.setText("Booking ID:");

		jButtonCancelRequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonCancelRequest.setText("Cancel Request");
		jButtonCancelRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonCancelRequest.addMouseListener(new java.awt.event.MouseAdapter() {
			
		});
		jButtonCancelRequest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonCancelRequestActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabelValid2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelValid2.setForeground(new java.awt.Color(255, 255, 255));
		jLabelValid2.setText("Duration(mins):");

		jLabelDuration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelDuration.setForeground(new java.awt.Color(255, 255, 255));

		jLabelValid3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelValid3.setForeground(new java.awt.Color(255, 255, 255));
		jLabelValid3.setText("Pay Time Stamp:");

		jLabelTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelTime.setForeground(new java.awt.Color(255, 255, 255));

		jLabelVerfication.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabelVerfication.setForeground(new java.awt.Color(255, 255, 255));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(23, 23, 23).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabelParkingSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
												javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextFieldLicense1,
														javax.swing.GroupLayout.PREFERRED_SIZE, 134,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBoxParkingSpot,
														javax.swing.GroupLayout.PREFERRED_SIZE, 134,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jButtonParkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(45, 45, 45)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelValid2).addComponent(jLabelValid3))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelDuration,
																javax.swing.GroupLayout.PREFERRED_SIZE, 125,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelTime,
																javax.swing.GroupLayout.PREFERRED_SIZE, 125,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelValid).addComponent(jLabelValid1))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelPayment,
																javax.swing.GroupLayout.PREFERRED_SIZE, 125,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelBookID,
																javax.swing.GroupLayout.PREFERRED_SIZE, 125,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(70, 70, 70)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jButtonAddSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonGrantRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(55, 55, 55)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButtonRemoveSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonCancelRequest, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 157,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(196, 196, 196).addComponent(
								jLabelVerfication, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
								javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 18,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldLicense1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelValid).addComponent(jLabelPayment))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
								.addComponent(jLabelParkingSpot, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBoxParkingSpot)
								.addComponent(jLabelValid1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelBookID, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(
										jButtonParkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelValid2, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelDuration))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
												.addComponent(jLabelValid3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelTime, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addGap(4, 4, 4)
						.addComponent(jLabelVerfication, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonGrantRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonCancelRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonAddSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonRemoveSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(31, 31, 31)));

		jPanel2.setBackground(new java.awt.Color(245, 205, 121));

		jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonLogout.setText("Logout");
		jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {

		});
		jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonLogoutActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(50, 50, 50));
		jLabel1.setText("Enforcement Officer Dashboard");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(73, 73, 73).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButtonLogout).addGap(45, 45, 45)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jButtonLogout)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
						.addGap(0, 20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(87, 87, 87).addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>

	private void jButtonParkStatusActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		String path = "database.csv";

		MaintainDatabase maintain = new MaintainDatabase();

		maintain.load(path);

		for (Database d : maintain.databaseList) {
			if ((d.getParkingLot() == Integer.valueOf(jComboBoxParkingSpot.getSelectedItem().toString()))
					&& d.getLicense().equals(jTextFieldLicense1.getText())) {
				if (d.getPaid() == true) {
					jLabelPayment.setText("Paid");
				} else {
					jLabelPayment.setText("Didn't Pay");
				}
				jLabelBookID.setText(Integer.valueOf(d.getbookID()).toString());
				jLabelDuration.setText(Integer.valueOf(d.getDuration()).toString());
				jLabelTime.setText(d.getTime());
				
				

			} else {
				jLabelBookID.setText("User not found!");
				jLabelPayment.setText("Parking Spot Vacant!");
				
			}

		}
		
		
	}

	private void jButtonRemoveSpaceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RemoveSpaceGUI OP = new RemoveSpaceGUI();
        OP.setVisible(true);
        OP.pack();
        OP.setLocationRelativeTo(null);
        OP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
	}

	private void jButtonAddSpaceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		AddSpaceGUI OP = new AddSpaceGUI();
        OP.setVisible(true);
        OP.pack();
        OP.setLocationRelativeTo(null);
        OP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
	}

	private void jButtonGrantRequestActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		String path = "database.csv";
		MaintainDatabase maintain = new MaintainDatabase();
		

		
		maintain.load(path);

			for(Database d: maintain.databaseList){
			if((d.getParkingLot() == Integer.valueOf(jComboBoxParkingSpot.getSelectedItem().toString())) && d.getLicense().equals(jTextFieldLicense1.getText())) {
				
				
					d.setValidated(true);
					maintain.update(path);
					jLabelVerfication.setText("Request Granted!");
				
				
			}
		
			}
	}

	private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		String path = "user.csv";
    	MaintainUser main = new MaintainUser();
    	 MaintainUser.logout(MaintainUser.emailString);
         main.update(path);
    	LandingGUI OP = new LandingGUI();
        OP.setVisible(true);
        OP.pack();
        OP.setLocationRelativeTo(null);
        OP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
	}

	private void jTextFieldLicense1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBoxParkingSpotActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonCancelRequestActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		String path = "database.csv";
		MaintainDatabase maintain = new MaintainDatabase();
		int parkingSpot = Integer.valueOf(jComboBoxParkingSpot.getSelectedItem().toString());
		String license = jTextFieldLicense1.getText();
        
	
			maintain.load(path);
			for(Database d: maintain.databaseList){
				
			
				if(parkingSpot == d.getParkingLot() && license.equals(d.getLicense())) {
				maintain.databaseList.remove(d);
				maintain.update(path);
				jLabelVerfication.setText("Cancelled Request!");
				
				}
			
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ParkOfficeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ParkOfficeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ParkOfficeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ParkOfficeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ParkOfficeGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonAddSpace;
	private javax.swing.JButton jButtonCancelRequest;
	private javax.swing.JButton jButtonGrantRequest;
	private javax.swing.JButton jButtonLogout;
	private javax.swing.JButton jButtonParkStatus;
	private javax.swing.JButton jButtonRemoveSpace;
	private javax.swing.JComboBox<String> jComboBoxParkingSpot;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelBookID;
	private javax.swing.JLabel jLabelDuration;
	private javax.swing.JLabel jLabelLicensePlate;
	private javax.swing.JLabel jLabelParkingSpot;
	private javax.swing.JLabel jLabelPayment;
	private javax.swing.JLabel jLabelTime;
	private javax.swing.JLabel jLabelValid;
	private javax.swing.JLabel jLabelValid1;
	private javax.swing.JLabel jLabelValid2;
	private javax.swing.JLabel jLabelValid3;
	private javax.swing.JLabel jLabelVerfication;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextFieldLicense1;
	// End of variables declaration
}
