import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vamsilingamaneni
 */
public class ViewBookingGUI extends javax.swing.JFrame {

    /** Creates new form ViewBooking */
    public ViewBookingGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jLabelEmaillabek = new javax.swing.JLabel();
        jLabelParkingS = new javax.swing.JLabel();
        jLabelValidPayment = new javax.swing.JLabel();
        jLabelPaylabel = new javax.swing.JLabel();
        jLabelbookidlabel = new javax.swing.JLabel();
        jLabelLicensePlatelabel = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelParkingSpot = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jLabelParkingSpot1 = new javax.swing.JLabel();
        jLabelLicensePLate = new javax.swing.JLabel();
        jLabelBookID = new javax.swing.JLabel();
        jLabelPayStatus = new javax.swing.JLabel();
        jButtonView = new javax.swing.JButton();
        jLabelParkingSpot2 = new javax.swing.JLabel();
        jLabelTimeRemain = new javax.swing.JLabel();
        jLabelConfirmation = new javax.swing.JLabel();
        jLabelLicensePlatelabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 98, 117));

        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
         
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelEmaillabek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmaillabek.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmaillabek.setText("Email:");

        jLabelParkingS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelParkingS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelParkingS.setText("Parking spot:");

        jLabelValidPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValidPayment.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPaylabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPaylabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaylabel.setText("Payment Status:");

        jLabelbookidlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelbookidlabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbookidlabel.setText("Booking ID:");

        jLabelLicensePlatelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLicensePlatelabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLicensePlatelabel.setText("License Plate:");

        jLabelEmail.setBackground(new java.awt.Color(108, 122, 137));
        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabelParkingSpot.setBackground(new java.awt.Color(108, 122, 137));
        jLabelParkingSpot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelParkingSpot.setForeground(new java.awt.Color(255, 255, 255));

        jLabelDuration.setBackground(new java.awt.Color(108, 122, 137));
        jLabelDuration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDuration.setForeground(new java.awt.Color(255, 255, 255));

        jLabelParkingSpot1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelParkingSpot1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelParkingSpot1.setText("Duration(mins):");

        jLabelLicensePLate.setBackground(new java.awt.Color(108, 122, 137));
        jLabelLicensePLate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLicensePLate.setForeground(new java.awt.Color(255, 255, 255));

        jLabelBookID.setBackground(new java.awt.Color(108, 122, 137));
        jLabelBookID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBookID.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPayStatus.setBackground(new java.awt.Color(108, 122, 137));
        jLabelPayStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPayStatus.setForeground(new java.awt.Color(255, 255, 255));

        jButtonView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonView.setText("View");
        jButtonView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonView.addMouseListener(new java.awt.event.MouseAdapter() {
          
        });
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonViewActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabelParkingSpot2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelParkingSpot2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelParkingSpot2.setText("Pay Time Stamp:");

        jLabelTimeRemain.setBackground(new java.awt.Color(108, 122, 137));
        jLabelTimeRemain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTimeRemain.setForeground(new java.awt.Color(255, 255, 255));

        jLabelConfirmation.setBackground(new java.awt.Color(108, 122, 137));
        jLabelConfirmation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfirmation.setForeground(new java.awt.Color(255, 255, 255));

        jLabelLicensePlatelabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLicensePlatelabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLicensePlatelabel1.setText("Confirmation:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelParkingS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEmaillabek, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelEmail)
                                        .addComponent(jLabelParkingSpot)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelParkingSpot1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDuration)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelParkingSpot2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTimeRemain)))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValidPayment)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPaylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPayStatus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelbookidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBookID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonView)
                                    .addComponent(jLabelLicensePlatelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLicensePlatelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLicensePLate)
                                    .addComponent(jLabelConfirmation)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButtonBack)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmaillabek, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelPayStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelParkingS)
                            .addComponent(jLabelParkingSpot)
                            .addComponent(jLabelbookidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBookID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelParkingSpot1)
                            .addComponent(jLabelDuration))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTimeRemain)
                            .addComponent(jLabelParkingSpot2)
                            .addComponent(jLabelLicensePlatelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConfirmation))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLicensePlatelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLicensePLate))
                        .addGap(145, 145, 145)
                        .addComponent(jLabelValidPayment)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 205, 121));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setText("View Booking");

        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
           
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogout))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

                                       

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	        CustomerGUI cGUI = new CustomerGUI();
                cGUI.setVisible(true);
                cGUI.pack();
                cGUI.setLocationRelativeTo(null);
                cGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
    }                                           

                                      

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

                                    

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                            
        // TODO add your handling code here:
	String path = "database.csv";
    	
		MaintainDatabase maintain = new MaintainDatabase();
		
		String email = MaintainUser.emailString;

	
			maintain.load(path);

				for(Database d: maintain.databaseList){
					if(email.equals(d.getEmail())) {
						jLabelEmail.setText(email);
						jLabelDuration.setText(Integer.valueOf(d.getDuration()).toString());
						jLabelParkingSpot.setText(Integer.valueOf(d.getParkingLot()).toString());
						jLabelBookID.setText(Integer.valueOf(d.getbookID()).toString());
						jLabelLicensePLate.setText(d.getLicense());
						jLabelTimeRemain.setText(d.getTime());
						
						if(d.getPaid() == true) {
						jLabelPayStatus.setText("Paid");
						}
						else if(d.getPaid() == false) {
							jLabelPayStatus.setText("Not Paid");
							}
						
						if(d.getValidated() == true) {
							jLabelConfirmation.setText("Confirmed");
							}
							else if(d.getValidated() == false) {
								jLabelConfirmation.setText("Not Confirmed");
								}
						
					}
				}
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBookID;
    private javax.swing.JLabel jLabelConfirmation;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmaillabek;
    private javax.swing.JLabel jLabelLicensePLate;
    private javax.swing.JLabel jLabelLicensePlatelabel;
    private javax.swing.JLabel jLabelLicensePlatelabel1;
    private javax.swing.JLabel jLabelParkingS;
    private javax.swing.JLabel jLabelParkingSpot;
    private javax.swing.JLabel jLabelParkingSpot1;
    private javax.swing.JLabel jLabelParkingSpot2;
    private javax.swing.JLabel jLabelPayStatus;
    private javax.swing.JLabel jLabelPaylabel;
    private javax.swing.JLabel jLabelTimeRemain;
    private javax.swing.JLabel jLabelValidPayment;
    private javax.swing.JLabel jLabelbookidlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   

}
